replicaCount: 1
image:
  repository: ghcr.io/bvandewe/events-player
  tag: latest
ports:
  containerPort: 80
service:
  type: ClusterIP # LoadBalancer # Adjust based on your environment needs
  port: 80
virtualService:
  host: test-events.domain.com
  gateway: istio-system/all-ccie-gateway
environment:
  api_log_level: DEBUG 
  api_log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  api_default_generator_gateways: '{\"urls\": [\"http://localhost/events/pub\"]}'
  api_browser_queue_size: 1000
