apiVersion: v1
kind: Service
metadata:
  name: attempts-aggregator
  namespace: mozart
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: attempts-aggregator
