apiVersion: v1
kind: Service
metadata:
  name: cloudevent-player
  namespace: mozart
spec:
  ports:
    - port: 8888
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app: cloudevent-player
